FROM registry.redhat.io/ubi9/go-toolset:1.24@sha256:6fd64cd7f38a9b87440f963b6c04953d04de65c35b9672dbd7f1805b0ae20d09 AS build-env

ENV GOEXPERIMENT=strictfipsruntime
ENV CGO_ENABLED=1

WORKDIR /ct_server
RUN git config --global --add safe.directory /ct_server
COPY . .
RUN go build -o ct_server -mod=readonly -trimpath ./trillian/ctfe/ct_server

# Install server
FROM registry.access.redhat.com/ubi9-minimal@sha256:4fef3a1e53399e64f839190483711d361455bd18274954ce4bec4845575df83e

# Create a non-root user and group with a home directory
RUN groupadd -r appgroup && \
    useradd -r -g appgroup -d /home/appuser -m -s /sbin/nologin appuser

COPY --from=build-env /ct_server/ct_server /usr/local/bin/ct_server
COPY LICENSE /licenses/license.txt

LABEL name="certifcate-transparency-server"
LABEL description="The binary responsible for providing the Certificate Transparency (CT) log server."
LABEL io.k8s.description="The binary responsible for providing the Certificate Transparency (CT) log server."
LABEL io.k8s.display-name="CT server container image for Red Hat Trusted Artifact Signer."
LABEL io.openshift.tags="CT-server, Red Hat trusted artifact signer."
LABEL summary="Provides the CT-server binary."
LABEL com.redhat.component="ct-server"

USER appuser

WORKDIR /home/appuser

# Set the binary as the entrypoint of the container
ENTRYPOINT ["ct_server"]
