FROM registry.redhat.io/ubi9/go-toolset:9.8-1790174511@sha256:0f2be9ed624fabfe8625ffa510d2b243766249006518e551ef9e0b486f195e90 AS build-env

ENV GOEXPERIMENT=strictfipsruntime
ENV CGO_ENABLED=1

WORKDIR /ct_server
RUN git config --global --add safe.directory /ct_server
COPY . .
RUN go build -o ct_server -mod=readonly -trimpath ./trillian/ctfe/ct_server

# Install server
FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:9c6d058e39cdbd97c9e0b83c5c394490869dfe96e8f9b3f0fbde0a08f4220adf

# Create a non-root user and group with a home directory
RUN groupadd -r appgroup && \
    useradd -r -g appgroup -d /home/appuser -m -s /sbin/nologin appuser

COPY --from=build-env /ct_server/ct_server /usr/local/bin/ct_server
COPY LICENSE /licenses/license.txt

LABEL name="rhtas/certificate-transparency-rhel9"
LABEL description="The binary responsible for providing the Certificate Transparency (CT) log server."
LABEL io.k8s.description="The binary responsible for providing the Certificate Transparency (CT) log server."
LABEL io.k8s.display-name="CT server container image for Red Hat Trusted Artifact Signer."
LABEL io.openshift.tags="CT-server, Red Hat trusted artifact signer."
LABEL summary="Provides the CT-server binary."
LABEL com.redhat.component="ct-server"

USER appuser

WORKDIR /home/appuser

# Set the binary as the entrypoint of the container
ENTRYPOINT ["ct_server"]
