apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/certificate-transparency-go?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
    build.appstudio.openshift.io/build-nudge-files: "controllers/constants/*"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: certificate-transparency-go
    appstudio.openshift.io/component: certificate-transparency-go
    pipelines.appstudio.openshift.io/type: build
  name: certificate-transparency-go-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: dockerfile
    value: Dockerfile.rh
  - name: git-url
    value: '{{source_url}}'
  - name: output-image
    value: quay.io/securesign/certificate-transparency-go:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: hermetic
    value: true
  - name: build-source-image
    value: true
  - name: prefetch-input
    value: [{"path": ".", "type": "gomod"}]
  - name: go_unit_test
    value: true
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: 'https://github.com/securesign/pipelines.git'
      - name: revision
        value: 'main'
      - name: pathInRepo
        value: 'pipelines/docker-build-oci-ta.yaml'
  taskRunTemplate: {}
  taskRunSpecs:
    - pipelineTaskName: run-unit-test
      serviceAccountName: appstudio-pipeline
      podTemplate:
        imagePullSecrets:
          - name: brew-registry-pull-secret
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
