apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/build-nudge-files: controllers/constants/*
    build.appstudio.openshift.io/repo: https://github.com/securesign/certificate-transparency-go?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "release-1.2"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: tas-components-v1-2
    appstudio.openshift.io/component: certificate-transparency-go-v1-2
    pipelines.appstudio.openshift.io/type: build
  name: certificate-transparency-go-v1-2-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: release-version
    value: 1.2.2
  - name: dockerfile
    value: Dockerfile.rh
  - name: git-url
    value: '{{source_url}}'
  - name: output-image
    value: quay.io/securesign/certificate-transparency-go:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: hermetic
    value: "true"
  - name: build-source-image
    value: "true"
  - name: prefetch-input
    value: '[{"path":".","type":"gomod"}]'
  - name: go_unit_test
    value: "true"
  pipelineRef:
    params:
    - name: url
      value: https://github.com/securesign/pipelines.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/docker-build-oci-ta.yaml
    resolver: git
  taskRunSpecs:
  - pipelineTaskName: run-unit-test
    podTemplate:
      imagePullSecrets:
      - name: brew-registry-pull-secret
    serviceAccountName: build-pipeline-certificate-transparency-go-v1-2
  taskRunTemplate:
    serviceAccountName: build-pipeline-certificate-transparency-go-v1-2
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
